sdk/src/main/java/com/google/cloud/dataflow/sdk/values/KV.java
I found myself having to write this:
KV&lt;String, Iterable&lt;String&gt;&gt; kv = KV.&lt;String, Iterable&lt;String&gt;&gt;of("foo", new ArrayList&lt;String&gt;());
When I would have preferred to write this:
KV&lt;String, Iterable&lt;String&gt;&gt; kv = KV.of("foo", new ArrayList&lt;String&gt;());
What do you think about this change?
=> Generalize type signature of KV.of

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/Combine.java
We are implementing a PipelineRunner for Apache Flink: http://flink.apache.org. Making the KeyedCombineFn accessible in Combine.PerKey would allow us to translate it to a more efficient runtime operation.
=> Make fn in Combine.PerKey Non-Transient, Add Getter

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/join/CoGbkResultSchema.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/join/KeyedPCollectionTuple.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/join/RawUnionValue.java
This pull request is similar to #8 in the sense that it exposes some internal API classes and fields. The intention is to write a custom `coGroupByKey` translator. For that, we need access to `CoGbkResultSchema`, `TaggedKeyedPCollection`, and `RawUnionValue`.
=> increase scope of a few classes to write APIs against them

checkstyle.xml
As discussed in https://github.com/GoogleCloudPlatform/DataflowJavaSDK/pull/10
With external contributors the copyright header should be:
Copyright (C) 2015 The Google Cloud Dataflow Authors
Old copyright header is still accepted.
=> Modify checkstyle to accept new copyright header.

examples/src/main/java/com/google/cloud/dataflow/examples/WindowingWordCount.java
When I've practiced with DataflowJavaSDK examples based on the documentation (https://cloud.google.com/dataflow/java-sdk/wordcount-example), I encountered the ERROR shown below with WindowingWordCount.
```
$ mvn exec:java -pl examples -Dexec.mainClass=com.google.cloud.dataflow.examples.WindowingWordCount -Dexec.args="--project=${PROJECT} --stagingLocation=${STAGING} --runner=BlockingDataflowPipelineRunner --output=${OUTPUT}"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Dataflow Java Examples - All manual_build
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> exec-maven-plugin:1.1:java (default-cli) > validate @ …
```
=> Fix a typo of method name in WindowingWordCount.Options.

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/Filter.java
I corrected an error in the filter JavaDoc. The example showed comparing numbers but the type was string. This generated confusion so I changed it to Integers.
=> Fixed error in examples of the Filter JavaDoc.

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/CalendarWindows.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/FixedWindows.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/Sessions.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/SlidingWindows.java
This change exposes fields of `WindowFn` subclasses. Needed for properly translating window functionality onto other backends - Apache Flink in my specific case.
The proposed change was discussed in #18.
=> Getters for unexposed WindowFn fields

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubIO.java
The Java doc for the format of a subscription string is incorrect.
=> Fix documentation of PubsubIO subscription format

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
Fixed typo in the doc. 
Window has ```into``` [method](https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/transforms/windowing/Window#into-com.google.cloud.dataflow.sdk.transforms.windowing.WindowFn-) but not ```info```
=> Fixed typo in doc

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BoundedReadFromUnboundedSource.java
`close()` is not called by wrapping `BoundedReadFromUnboundedSource` resulting in finalization behavior for the `UnboundedSource` not executing.
=> Fixed close not being called

contrib/hadoop/AUTHORS.md, contrib/hadoop/README.md, contrib/hadoop/pom.xml, contrib/hadoop/src/test/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSourceTest.java, contrib/hadoop/src/test/java/com/google/cloud/dataflow/contrib/hadoop/WritableCoderTest.java
hadoop contrib: make it compile against latest
- Update version to recommended [1.0.0,2.0.0)
- SourceTestUtils moved packages
- Removed test-jar from pom.xml
- Fixup path to javadoc folders
- Java syntax highlighting in README.md
Now, `mvn verify` passes when run in the `contrib/hadoop` folder.
=> Fixup PR #47

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/worker/StateSampler.java
Mismatching keys were being used for get and set in the statesByName map, causing the state/counter existence check to always fail and every invocation of stateForName() to create a new counter and state.
This manifests as a memory leak where the majority of the heap is consumed by the contents of statesByName and kindsByState, ultimately causing the worker to fail.
=> worker: fix leak in StateSampler

examples/src/main/java/com/google/cloud/dataflow/examples/WindowedWordCount.java
It appears that truncate mode is not supported for unbounded
PCollection.
Error message:
[ERROR] Failed to execute goal
org.codehaus.mojo:exec-maven-plugin:1.1:java (default-cli) on
project
google-cloud-dataflow-java-examples-all: An exception occured while
executing th
e Java class. null: InvocationTargetException:
WriteDisposition.WRITE_TRUNCATE is not supported for unbounded
PCollections or when using tablespec functions. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with
the
-e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug
logging.
[ERROR]
[ERROR] For more information about the errors and possible
solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExc …
=> Change BQ mode to append instead of truncate

.travis.yml, examples/src/main/java/com/google/cloud/dataflow/examples/WindowedWordCount.java
* See travis-ci/travis-ci#3396. Basically, there's an error that does not properly pass -Xmx and similar arguments to the forked JVMs that Javadoc, Surefire, and other plugins invoke. This bug causes the forked JVMs to exceed the container's RAM limit, the JVMs to get killed, and the builds to fail.
Disabling the forking by setting `-DforkCount=0` in the Maven command seems to have resolved the issue, and it does not slow down build time much.
* However, the underlying bug seems to only affect Linux VMs, and not OS X. Additionally, disabling forking in the OS X tests causes them to fail for another lingering Travis issue (PermSize in OS X). So, I rewrote the test matrix to only disable forking with the above argument for Linux tests.
* In the cleanup, I rewrote the test matrix for Travis …
=> Disable Maven forking in Travis-CI to fix build issues

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java
=> Backport apache/incubator-beam#64

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/AbstractModelEnforcement.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/EncodabilityEnforcementFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityEnforcementFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ModelEnforcement.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ModelEnforcementFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/EncodabilityEnforcementFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityEnforcementFactoryTest.java
ModelEnforcements ensure that user-written code conforms to the model,
in order to ensure that it is portable between runners.
Add EncodabilityEnforcement and ImmutabilityEnforcement.
EncodabilityEnforcement ensures that all values can be encoded.
ImmutabilityEnforcement ensures that values are not mutated within the
processing of a Bundle.
Backports https://github.com/apache/incubator-beam/pull/74
=> Add ModelEnforcements

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/Repeatedly.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/windowing/RepeatedlyTest.java
Previously, Repeatedly#onFire only cleared the finished bits associated
with the root of the sub-tree, as demonstrated by the new unit tests.
This led to problems with AfterFirst#shouldFire, which checked to see if
any of the sub-triggers have their finished bits set.
Now, Repeatedly#onFire calls #resetTree, which clears all the finished
bits in the entire sub-tree.
=> Backport apache/incubator-beam#110

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessTimerInternals.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayData.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/CombineFnUtil.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/LateDataDroppingDoFnRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PaneInfoTracker.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PropertyNames.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnContextFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/TimerInternals.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/Timers.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/TriggerContextFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/TriggerRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/WatermarkHold.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/state/StateTags.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CountingInputTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslatorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/ReduceFnTester.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/TriggerTester.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/state/StateTagTest.java
=> Backport apache/incubator-beam#65

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunner.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunnerTest.java
Previously, the sequence was:
1. Map a window to a representative of its equivalence class
according to merging.
2. Drop the element if that window was closed.
But this crashes if the original window was already closed.
The new sequence is reversed. This is safe, because it is not possible
to map to a representative which is closed, as it is no longer a
candidate for merges.
=> Backport apache/incubator-beam#105

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BoundedReadEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactory.java
This permits use of sources that are not the initial source used in the
transform.
BoundedSource#splitIntoBundles and UnboundedSource#generateInitialSplits
generate multiple source objects for the same transform in order to
permit parallelism.
Also some cleanups:
- Use proper scoping, interfaces in BoundedReadEvaluator
- Use BoundedReader instead of Reader
- contentsRemaining should be method-scoped not instance-scoped
This backports [Beam #106](https://github.com/apache/incubator-beam/pull/106)
=> Explicitly track the Source a ReadEvaluator is using

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/CompletionCallback.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java
This allows a configurable application of Model Enforcement based on the
class of transform being executed, both before and after an element is
processed and after the transform completes.
This backports [Beam #82](https://github.com/apache/incubator-beam/pull/82)
=> Execute ModelEnforcements in TransformExecutor

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ConsumerTrackingPipelineVisitor.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ConsumerTrackingPipelineVisitorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java
Fix a bug where steps would only be given step names if they were a
non-root node.
Use the ConsumerTrackingPipelineVisitor in the
InProcessEvaluationContext test to handle runner-expanded transforms
This backports [Beam #113](https://github.com/apache/incubator-beam/pull/113)
=> Give root transforms step names

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessCreate.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessCreateTest.java
This allows dynamic splits to be exercised in the create.
Backports [Beam #91](https://github.com/apache/incubator-beam/pull/91)
=> Implement InProcessCreate with an OffsetBasedSource

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityCheckingBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/BoundedReadEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/FlattenEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/GroupByKeyEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManagerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoMultiEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoSingleEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ViewEvaluatorFactoryTest.java, sdks/java/core/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityCheckingBundleFactoryTest.java, sdks/java/core/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactoryTest.java
This allows checks to be made on the contents of bundles.
ImmutabilityCheckingBundleFactory produces bundles that ensure that
elements output to a bundle are not modified after being output.
This backports [Beam #86](https://github.com/apache/incubator-beam/pull/86)
=> Add BundleFactory, ImmutabilityCheckingBundleFactory

examples/src/main/java/com/google/cloud/dataflow/examples/DebuggingWordCount.java, maven-archetypes/examples/src/main/resources/archetype-resources/src/main/java/DebuggingWordCount.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/options/CloudDebuggerOptions.java
Backport PR #115 and #108
R:@davorbonaci
=> Backport debugger changes

sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java
Backports [BEAM #92](https://github.com/apache/incubator-beam/pull/92)
=> Add TextIO and AvroIO withNumShards tests

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/PassthroughTransformEvaluator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformEvaluatorRegistry.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/WindowEvaluatorFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/WindowEvaluatorFactoryTest.java
This is a TransformEvaluator-based implementation of the Window#into
primitive, as opposed to the DoFn ProcessContext internals-based
implementation.
This backports [BEAM #149](https://github.com/apache/incubator-beam/pull/149)
=> Add WindowIntoEvaluatorFactory

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessRegistrar.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRegistrarTest.java
Adds @AutoService for the InProcessPipelineRunner and
InProcessPipelineOptions
This backports [BEAM #169](https://github.com/apache/incubator-beam/pull/169)
=> Add InProcessRegistrar

sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslatorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/EncodabilityEnforcementFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataTest.java
----Release Notes----
[]
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=119217803
=> Integration fixes

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/Write.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/WriteTest.java
And do not supply a timestamp when outputting.
Note that this is safe because the functions in the Writer cannot access the window
or timestamp. When we add per-Window or similar functions to the sinks, we will
likely do so at a higher level.
This is a backport of apache/incubator-beam#188
=> [BEAM-188] Write: apply GlobalWindows first

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java
This is a partial backport of https://github.com/apache/incubator-beam/pull/199
=> BigtableIO: switch to ProtoCoder from deprecated Proto2Coder

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
If runners override the transform, validation will still happen.
Backport of apache/incubator-beam#197
=> BigQueryIO: move write validation to validate() from apply()

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/DoFnRunnerBase.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/WindowedValue.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/WindowedValueTest.java
This takes an existing WindowedValue and returns a Collection of
WindowedValues, each of which is in exactly one window.
Use the explode implementation on DoFnRunnerBase
Backports [BEAM #206](https://github.com/apache/incubator-beam/pull/206)
=> Add WindowedValue#explodeWindows

checkstyle.xml
backported from apache/incubator-beam#245
=> checkstyle.xml: blacklist repackaged code from Google API Client

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManagerTest.java
This allows the WindowedValues to be partially completed while the
still holding the watermark.
This backports [BEAM #207](https://github.com/apache/incubator-beam/pull/207)
=> Track pending elements via exploded WindowedValues

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessCreate.java
Return 1L when there are no elements, as the default value. Return 1L
when the total encoded size of all the elements is 0, for example when
using VoidCoder.
Backports [BEAM-232](https://github.com/apache/incubator-beam/pull/232)
=> Fix CreateSource#getBytesPerOffset

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/GroupByKeyEvaluatorFactory.java
This ensures that the values are not dropped if they are exploded (for
example, in the Watermark Manager).
This backports [BEAM-242](https://github.com/apache/incubator-beam/pull/242)
=> Output InProcessGroupByKeyOnly elements in the Global Window

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactoryTest.java
The property of keyedness belongs to a PCollection. A BundleFactory
propogates the key as far as possible, but does not track if a bundle is
keyed.
This backports [BEAM #201](https://github.com/apache/incubator-beam/pull/201)
=> Remove isKeyed property of InProcess Bundles

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainer.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainerTest.java
This checks to ensure that the PCollectionView in the SideInputWindow
for the provided window either has elements available or is empty.
Schedule a future to ensure that the SideInputWindows are appropriately
filled with an empty iterable after retreiving the element.
Backports [BEAM #220](https://github.com/apache/incubator-beam/pull/220)
=> Allow InProcess Evaluators to check Side Input completion

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/DataflowPipelineOptions.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/BlockingDataflowPipelineRunnerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunnerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTest.java
This ensures that whenever a DataflowPipelineRunner is created, the
jobName of the created options conforms to the requirements of the
Dataflow Service.
This backports [BEAM #187](https://github.com/apache/incubator-beam/pull/187)
This backports [BEAM #233](https://github.com/apache/incubator-beam/pull/233)
=> Enforce JobName Preconditions in the Dataflow Runner

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
Update DataflowPipelineRunner.java to use worker harness container image corresponding to 1.5.1 release.
R: @lukecwik.
=> Worker harness container image update

examples/src/main/java/com/google/cloud/dataflow/examples/common/DataflowExampleUtils.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/options/PipelineOptionsFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJob.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessCreate.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainer.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/TestDataflowPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/DoFnReflector.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/IntraBundleParallelization.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/MutationDetectors.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/RestoreSystemProperties.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/GcsUtilTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/ReduceFnTester.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/TriggerTester.java
It is slated to be deprecated:
https://github.com/google/guava/commit/49e7d716f0f72d00c490864c3d11b815cfe93ec4
=> DataflowJavaSDK: remove all uses of Throwables.propagate

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java
Because the WatermarkManager is not synchronized within the call to
updatePending, the sequence in which pending queues are updated must be
in such a manner as to add additional restrictions, then remove any
restrictions which no longer apply. This ensures any intermediate read
will see at worst a more restricted watermark than the actual watermark.
Backports [BEAM #264](https://github.com/apache/incubator-beam/pull/264)
=> Fix update sequence in InMemoryWatermarkManager

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BoundedReadEvaluatorFactory.java
The reader is already closed by virtue of being the target of the
try-with-resources block that encompasses all of #finishBundle().
This backports [BEAM #257](https://github.com/apache/incubator-beam/pull/257)
=> Remove redundant close in BoundedReadEvaluatorFactory

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/EncodabilityEnforcementFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityCheckingBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityEnforcementFactory.java
This is excessively slow and also not useful, as coders are required to
be thread-safe
Backports [Beam #261](https://github.com/apache/incubator-beam/pull/261)
=> Stop cloning coders in the InProcessRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/Write.java
This will help, for all sinks, users and developers gain insight into where time
is spent. (Enabling DEBUG level will provide more insight.)
This is a backport of apache/incubator-beam#279
=> Write: add limited logging

sdk/pom.xml
https://github.com/apache/incubator-beam/pull/321
Note that maven archetypes already depends on guava 19.0
Also, note that I explicitly bring in google-auth-library-oauth2-http so it matches the incubator-beam version. Normally bigtable client brings in version 0.3.1
=> Backport incubator-beam PR #321

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactoryTest.java
When a bundle is partially completed, the unprocessed elements must be
placed in a new bundle to be processed at a later time. The bundle in
which they are processed should also have identical properties to the
bundle which the elements were initially present in.
withElements provides a simple way to create a "copy" of a bundle that
contains different elements.
This backports [BEAM #231](https://github.com/apache/incubator-beam/pull/231)
=> Add withElements to CommittedBundle

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainer.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReadyCheckingSideInputReader.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainerTest.java, sdks/java/core/src/main/java/org/apache/beam/sdk/util/PushbackSideInputDoFnRunner.java, sdks/java/core/src/test/java/org/apache/beam/sdk/util/IdentitySideInputWindowFn.java, sdks/java/core/src/test/java/org/apache/beam/sdk/util/PushbackSideInputDoFnRunnerTest.java
Backports [Beam #258](https://github.com/apache/incubator-beam/pull/258)
=> Add PushbackDoFnRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/WindowEvaluatorFactory.java
Fixes a NullPointerException when constructing the transform result.
This is a partial backport of [Beam #147](https://github.com/apache/incubator-beam/pull/147), with the minimum changes required for the InProcessPipelineRunner.
Required as a prerequisite to #255
=> Correctly pass the transform in WindowEvaluatorFactory

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/CommittedResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/CommittedResultTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManagerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java
Return as the output to InProcessEvaluationContext#handleResult(). This
allows a richer return type to improve possible behaviors when a result
is returned.
Use this object in the InMemoryWatermarkManager.
Backports [Beam #260](https://github.com/apache/incubator-beam/pull/260)
Backports [Beam #265](https://github.com/apache/incubator-beam/pull/265)
=> Add CommittedResult

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoMultiEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoSingleEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/SerializableCloningThreadLocalCacheLoader.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/SerializableCloningThreadLocalCacheLoaderTest.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ThreadLocalInvalidatingTransformEvaluator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ThreadLocalInvalidatingTransformEvaluatorTest.java
This allows the runner to avoid cloning DoFns for every input bundle.
Backports [Beam #320](https://github.com/apache/incubator-beam/pull/320)
=> Reuse DoFns in ParDoEvaluators

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BoundedReadEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/BoundedReadEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorServicesTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactoryTest.java
Null TransformEvaluators for sources represent a source where all splits
are currently in use or completed.
Update TransformExecutor to handle null evaluators properly.
Change TransformExecutor to a Runnable.
Backports [Beam #310](https://github.com/apache/incubator-beam/pull/310)
=> Return null evaluators from Unavailable Reads

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/AvroIOShardedWriteFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ShardControlledWrite.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TextIOShardedWriteFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/AvroIOShardedWriteFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TextIOShardedWriteFactoryTest.java
This is used for TextIO and AvroIO, which provide withNumOutputShards
methods to control the number of output files. Apply this override in
the InProcessPipelineRunner.
Backports [Beam #148](https://github.com/apache/incubator-beam/pull/148)
=> Add ShardControlledWrite override

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessTransformResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/StepTransformResult.java
The InProcessPipelineRunner expects some result values to be non-null.
Enforce those early.
Backports [Beam #153](https://github.com/apache/incubator-beam/pull/153)
=> Enforce non-null preconditions

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainer.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessSideInputContainerTest.java
Backports Beam [#318](https://github.com/apache/incubator-beam/pull/318) and [#326](https://github.com/apache/incubator-beam/pull/326)
=> Use AtomicReference in InProcessSideInputContainer

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/FixedThreadPoolExecutorServiceFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineOptions.java
Partial backport of Beam [#319](https://github.com/apache/incubator-beam/pull/319)
=> Switch to using a FixedThreadPool in the InProcessPipelineRunner

sdk/pom.xml, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/DataflowAssertTest.java
Improves coverage of the InProcessPipelineRunner
Preferably merged after #261
=> Run RunnableOnServiceTests with the InProcessPipelineRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandler.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayData.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandlerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslatorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataTest.java
PipelineOptions has been improved to generate display data
to be consumed by a runner and used for display. However, there
was a bug in the ProxyInvocationHandler implementation of
PipelineOptions display data which was causing NullPointerExceptions
when generated display data from PipelineOptions previously
deserialized from JSON.
This change also makes our error handling for display data exceptions
consistent across the Dataflow runner: exceptions thrown during
display data population will propogate out and cause the pipeline to
fail. This is consistent with other user code which may throw
exceptions at pipeline construction time.
(cherry picked from commit 1e669c44c9d2448b55f5bdba3dcff1831b2cd8b4)
=> Backport: Fix bug in PipelineOptions DisplayData serialization

sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslatorTest.java
These tests were written against the v1.5.0 tag, so they ensure that subsequent releases do not deviate from the translation there.
=> Change-detector test for PubsubIO translation

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandler.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/DisplayDataValidator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayData.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunnerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataTest.java
Display data can be added to any PTransform to be used
for display from any runner. Runners are not required to
consume display data, and currently many don't.
This changes InProcessRunner to consumer display data (and then
discard it) in order to validate that display data is properly
implemented on transforms within a pipeline. Exceptions thrown
within HasDisplayData implementations will cause Pipeline.run()
to fail.
(cherry picked from commit ac98c4a01f7e4b2bba3e99271b66e141e7555de8)
=> Backport: Evaluate display data from InProcessPipelineRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/GroupByKeyEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityCheckingBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessExecutionContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/StepAndKey.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/StructuralKey.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/GroupByKeyEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityCheckingBundleFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManagerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunnerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessTimerInternalsTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoInProcessEvaluatorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoMultiEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoSingleEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/StructuralKeyTest.java
This fixes problems with lookup by basing entirely on structural
equality.
Backports [Beam PR 411](https://github.com/apache/incubator-beam/pull/411)
=> Use Structural Value keys instead of User Values

sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunnerTest.java
=> Remove byteArrayCount timeout

sdk/pom.xml, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BundleFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ConsumerTrackingPipelineVisitor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessBundleOutputManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessTimerInternals.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessTransformResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/StepTransformResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformEvaluator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformEvaluatorFactory.java
Only publicly used elements are visible.
Remove javadoc exclusion for the runner.
=> Reduce Visibility of InProcessPipelineRunner implementations

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/WatermarkCallbackExecutor.java
This fixes a resource leak where the executor service is not properly
shut down with the rest of the InProcessPipelineRunner.
=> Use a DirectExecutor for Watermark Callbacks

pom.xml
exec-maven-plugin has a bad interaction with DataflowPipelineRunner
when waiting on daemon threads. When running example pipelines,
Maven will emit a warning saying background threads are alive
after being aborted. This looks to users like an error while there's
actually no harm to it. Disabling cleanupDaemonThreads suppresses
this warning.
(cherry picked from commit 70ba4f0dd63d564205b58d0ba4e5215f6802f8c9)
=> Backport: Disable exec-maven-plugin cleanupDaemonThreads

maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml, maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml, maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml
(cherry picked from commit 51030829ef53001eb7db608fd56bcf1b4bea4249)
---
The changes for the backport are a manually-apply of the diff from the above change because the files have been moved to a different location and Git wasn't able to figure it out automatically.
=> Backport: Port cleanupDaemonThreads fix to archetype module

examples/src/main/java/com/google/cloud/dataflow/examples/WindowedWordCount.java
The timestamps added in the WindowedWordCount example are currently
based on when the bundles are executed, which makes the min/max bounds
non-deterministic. This change makes the range  based on the
construction time.
(cherry picked from commit 335202a033ced6f30f1b0e5df9da047241abc750)
=> Backport: Make example AddTimestampFn range deterministic

sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CompressedSourceTest.java
We should use random.nextBytes(buff) instead of making the array in a loop.
The code we now point to is the same as the for loop, so the test continues to pass.
Backport of https://github.com/apache/incubator-beam/pull/456
=> CompressedSourceTest: simplify

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/display/package-info.java
(cherry picked from commit 2e0836e730c52c0ef7137f67495f43bb4ec2b06a)
=> Backport: Package javadoc for org.apache.beam.sdk.transforms.display

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactoryTest.java
Reuse up to a point, and then discard the reader to exercise resume from
checkpoint.
Backports https://github.com/apache/incubator-beam/pull/460
=> Reuse UnboundedReaders in the InProcessRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/AfterWatermark.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/windowing/AfterWatermarkTest.java
Window transforms register display data for the associated trigger
function by calling its .toString() method. The AfterWatermark
trigger .toString() method was not properly handling cases where
there is no late firings registered.
(cherry picked from commit e7f2f582afd48bf5e2aacb3a36471377cb927018)
=> Backport: Fix NullPointerException in AfterWatermark display data

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJob.java
This is backport from: https://github.com/apache/incubator-beam/pull/549
=> Backport from Beam: Increase the MESSAGES_POLLING_ATTEMPTS for slow backend starts

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/AvroSource.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroSourceTest.java
commons-compress defaults to a 32K buffer size for Snappy.
However, Avro uses xerial.snappy to write, which has a 64K buffer size.
When the buffer size is too small, decoding data from Snappy can cause
an EOF exception rather than finishing data.
This fixes BEAM-422.
=> AvroSource: use a 64K buffer size for Snappy codec

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/DoFnRunnerBase.java
An error message is printed when a DoFn needs access to the window but does
not implement RequiresWindowAccess. This PR changes to the error message
to print the interface name instead of just "RequiresWindow", which makes it
more clear which interface the user should use.
=> Clarify RequiresWindowAccess error message

sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/EntityCoder.java
Prevents localization issues where the product name is translated by mistake to a local language.
=> Minor nit on Datastore capitalization

examples/src/main/java/com/google/cloud/dataflow/examples/complete/AutoComplete.java
- To provide strongly consistent reads of entities written to Datastore, we need to use ancestor keys.
=> Use Datastore AncestorKey for AutoComplete example

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadDeduplicator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadDeduplicatorTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactoryTest.java
This ensures that sources that produce duplicate elements that are
marked as requiresDeduplication are handled by the DirectRunner.
Backports https://github.com/apache/incubator-beam/pull/473
=> Deduplicate Unbounded Reads

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/BoundedReadEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactory.java
The getTransformEvaluator() method's only call is poll on the result of
getTransformEvaluatorQueue (which is only ever called by
getTransformEvaluator). Instead, move the construction to
getTransformEvaluator and call poll on the result.
Backports https://github.com/apache/incubator-beam/pull/747
=> Remove unneccessary method in ReadEvaluatorFactories

sdk/pom.xml
Previously, guava-testlib guava-testlib was being relocated as part of
the shading process, but test-scope dependencies aren't bundled in the
uber-jar. As a result, the output JAR was unusable without recreating
the same shading rules in a consuming project.
=> Exclude guava-testlib from shading relocation

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/CounterSet.java
Some runners want to query CounterSet from a different thread than the one that mutates it. This requires thread safety.
=> Update CounterSet.java to be threadsafe

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/range/ByteKeyRangeTracker.java
It's the only unsynchronized function, and it could potentially produce bad data.
=> ByteKeyRangeTracker: synchronize toString

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java
This removes the need for an explicit break by ensuring that work added
by the monitor will not complete and add more work for the monitor to
complete.
backports https://github.com/apache/incubator-beam/pull/745
=> Apply ExecutorUpdates in two Phases

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImplTest.java
Additional fixups:
1. Uses the default MAX_RPC_ATTEMPTS, and reduced number of the parameters.
2. Uses errorExtractor
3. Removed testExportJobDoesNotExist, since it is same as testReadFromTable.
4. Adds getJob() unit tests.
=> Merge pr 331, with some fixups

sdk/pom.xml
The previous fix was incorrect in that the exclude pattern requires `.*` at the end. Tested this iteration using `javap` to inspect generated `.class` files.
=> Fix repackaging exclude pattern for guava-testlib

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/TimerInternals.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/GroupAlsoByWindowsProperties.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/TimerInternalsTest.java
Timers are equal if the domain, timestamp, and namespace are equal.
Compare these values in compareTo. The ordering of TimerData that are
not in the same namespace or domain is arbitrary.
Update GroupAlsoByWindowsProperties to ignore ordering of output
values, as this is not part of the requirements of a GroupAlsoByWindows
implementation.
in part backports https://github.com/apache/incubator-beam/pull/813
Requires review for GroupAlsoByWindowsProperties update.
=> Make TimerData#compareTo consistent with equals

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GatherAllPanes.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/GatherAllPanesTest.java
This PTransform Reifies and gathers all panes produced for each
window, outputting a single pane per window at the time the window is
Garbage Collected.
For use in DataflowAssert, to match over the final contents of each
window.
backports https://github.com/apache/incubator-beam/pull/180
backports minor additional changes to GatherAllPanes in Beam HEAD
=> Add GatherAllPanes PTransform

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/V1Beta3.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/datastore/V1Beta3Test.java
- Backport from https://github.com/apache/incubator-beam/pull/833
- DatastoreIO doesn't have an atomic operations, making WriteOperation#(initialize/finalize) a noop. There is no benefit for the additional complexity the Sink API brings. Hence cleaning up those classes and directly using a ParDo to implement Datastore writes.
=> DatastoreIO Sink as ParDo

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/SourceTestUtils.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/SourceTestUtilsTest.java
Backport https://github.com/apache/incubator-beam/pull/835/
=> Backport Beam PR-835 "Fix NPE in BigQueryIO.TransformingReader when it contains an unsplittable reader."

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/OffsetBasedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java
Reorders the code in some splitAtFraction calls so that the rangeTracker update
is the last thing (besides assignment) in the function. This avoids a potential
issue if creating the primary or residual sources happens to throw an exception.
=> BoundedReader: update the range last of all

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java
Otherwise, even temporary bursts of data will cause failures as the thread pool's queue is saturated.
R: @dhalperi
=> Run rejected BigQueryTableInserter tasks in the calling thread

sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/DataflowAssert.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/PaneExtractors.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/StaticWindows.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/TestDataflowPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/WindowSupplier.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/DataflowAssertTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/PaneExtractorsTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/StaticWindowsTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/WindowSupplierTest.java
This backports the GroupByKey-based PAssert, plus Window and Pane matching.
Additionally, it implements and deprecates DataflowAssert#thatIterable in order to maintain
backwards compatibility, and expands the IterableAssert and SingletonAssert interfaces to
maintain method visibility.
Backports https://github.com/apache/incubator-beam/pull/471
Backports https://github.com/apache/incubator-beam/pull/518
Backports https://github.com/apache/incubator-beam/pull/532
=> Backport Beam changes to PAssert

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/WriteWithShardingFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/FileIOChannelFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/WriteTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/WriteWithShardingFactoryTest.java
Add a Write Override Factory that limits the number of shards if
unspecified. This ensures that we will not write an output file per-key
due to bundling.
Do so by obtaining a count of the elements and obtaining the number of
shards based on the number of outputs.
backports https://github.com/apache/incubator-beam/pull/651
=> Dynamically choose number of shards in the InProcessPipelineRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
BigQuery has changed their total size quota to 12 TiB.
https://cloud.google.com/bigquery/quota-policy#import
This backports apache/incubator-beam#877
=> BigQueryIO.Write: raise size limit to 11 TiB

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/CommittedResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/CompletionCallback.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessTransformResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/StepTransformResult.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ViewEvaluatorFactory.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/CommittedResultTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManagerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/StepTransformResultTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java
The Executor should add work whenever it becomes Quiescent.
Track the amount of outstanding work in the executor, and
modify the state appropriately whenever work is scheduled or completes.
Backports https://github.com/apache/incubator-beam/pull/754
=> Use Quiescence to Drive the DirectRunner

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineOptions.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/KeyedResourcePool.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/LockedKeyedResourcePool.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/NanosOffsetClock.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TestStreamEvaluatorFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformEvaluatorRegistry.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/WriteWithShardingFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/DataflowAssert.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/PaneExtractors.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/TestStream.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/LockedKeyedResourcePoolTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TestStreamEvaluatorFactoryTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/TestStreamTest.java
This is a source suitable for use with tests that have interesting
triggering behavior. It is an Unbounded source that emits elements in
bundles, and advances the watermark and processing time appropriately.
TestStream is currently only supported in the InProcessPipelineRunner.
backports https://github.com/apache/incubator-beam/pull/817
backports https://github.com/apache/incubator-beam/pull/907
=> Add the TestStream Primitive

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java
This fixed https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/405
=> Create the temp dataset in the same location as the queried table in BigQueryTableRowIterator

examples/src/main/java/com/google/cloud/dataflow/examples/common/DataflowExampleUtils.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BoundedReadFromUnboundedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/DatastoreIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJob.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/AttemptAndTimeBoundedExponentialBackOff.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/AttemptBoundedExponentialBackOff.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/FluentBackoff.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GcsUtil.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/IntervalBoundedExponentialBackOff.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PackageUtil.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJobTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/AttemptAndTimeBoundedExponentialBackOffTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/AttemptBoundedExponentialBackOffTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImplTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/FluentBackoffTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/GcsUtilTest.java
We have 3 different backoff classes, which don't really have that much
different functionality. Add a single, flexible backoff implementation
that can be used to replace all three classes. Additionally, this new
backoff actually supports more functionality than any of the other three
did -- you can limit retries, cap the exponential growth of an
individual backoff, and cap the cumulative time spent in backoff; prior
implementations did not allow all 3.
This also makes the parameters self-obvious (Duration, not
number-that-is-also-millis) where appropriate.
This initial PR should have no functional changes.
* Implement FluentBackoff
* Replace other custom BackOff implementations with FluentBackoff
This is a backport of apache/incubator-beam#888
=> FluentBackoff: a replacement for a variety of custom backoff implementations

sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java
Fixes this break: https://travis-ci.org/GoogleCloudPlatform/DataflowJavaSDK/builds/158022392
Since both PRs passed, I can only assume this is some weird conflict between Pei's PR and my PR.
#411 and #417
=> BigQueryTableRowIteratorTest: fix bug that resulted from merge conflict

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java
Before the backoff would grow unboundedly, so we could in principle wait
1.5x to 2x the actual job time. For long running jobs this is hours.
Now, we just back off at most 1 minute between checking the job state.
Note there should be no danger of QPS overload here because we should
have very few concurrent outstanding jobs
This is a backport of apache/incubator-beam#917
=> BigQuery: limit max job polling time to 1 minute

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java
The new code in https://github.com/GoogleCloudPlatform/DataflowJavaSDK/pull/411 did
not adequately handle the case in which a query does not reference any tables, which
could result in a NullPointerException.
=> BigQueryTableRowIterator: support queries that refernece no tables

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java
=> Backport Apache Beam PR/934

examples/src/main/java8/com/google/cloud/dataflow/examples/complete/game/LeaderBoard.java, examples/src/test/java8/com/google/cloud/dataflow/examples/complete/game/LeaderBoardTest.java
This test exercises the PTransforms that make up the LeaderBoard
example. This includes speculative and late trigger firings to produce
team and individual scores on a global and fixed window basis.
Refactor LeaderBoard to expose the team and user score calculations as
composite PTransforms to enable this testing.
backports https://github.com/apache/incubator-beam/pull/854
=> Add LeaderBoardTest

sdk/src/test/java/com/google/cloud/dataflow/sdk/coders/JAXBCoderTest.java
The infrastructure should kill the test if the await does not return.
This backports https://github.com/apache/incubator-beam/pull/925
=> Remove timeout in JAXBCoderTest

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/DataflowPipelineWorkerPoolOptions.java
We are moving towards supporting only TEARDOWN_ALWAYS VM teardown policy.
=> Deprecate TeardownPolicy for Dataflow service

checkstyle.xml, maven-archetypes/examples/src/main/resources/archetype-resources/src/main/java/DebuggingWordCount.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/CloudObject.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/OutputReference.java
Apparently the IllegalImport check only blocks packages,
so we had to move to Regexp to get individual classes.
This is a backport of apache/incubator-beam#872
=> checkstyle: prohibit API client repackaged Guava

checkstyle.xml
This is a backport of apache/incubator-beam#972
=> checkstyle.xml: blacklist imports of two shaded dependencies

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIOTest.java
This is a backport of apache/incubator-beam#969
=> [BEAM-639] BigtableIO: add support for users to scan table subranges

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PropertyNames.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java
BigQuery 2.0 adds a new dialect of SQL, Standard SQL, and we need to
enable passing a specific option to BigQuery's APIs in order to support
it.
=> BigQueryIO: enable users to control the SQL dialect

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserterTest.java
This is a backport of apache/incubator-beam#1018
Please scrutinize because the rebase did not apply at all -- the code is in different files entirely.
=> BigQueryTableInserter: fix issues in insertAll and add better tests

sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/DoFnTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/DoFnWithContextTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/WithTimestampsTest.java
These tests aren't truly portable across runners, as excepitons thorwn
on failure may be different.
=> Remove RunnableOnService with tests with ExpectedException

sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BoundedReadFromUnboundedSourceTest.java
1) Tests actually require non-splitting source (assert that the Key is 0).
Use withoutSplitting.
2) Indentation and unused code (expectedOutput).
3) For these time-based tests, runners cannot guarantee we'll produce
at least 3 elements, but we can expect there to be at least 1.
These appear in Beam but were not backported:
https://github.com/apache/incubator-beam/commit/fecd0362f5c1710c7fee0b2a03cc8549d1b8f75a
https://github.com/apache/incubator-beam/commit/ee7272fe77d78240c6f8e0b79cdc93b460171b8c
=> BoundedReadFromUnboundedSourceTest: fixes

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
R: @dhalperi 
This conflicts with PR-453, needs a rebase before merging.
=> BigQueryQuerySource: support queries that refernece no tables

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BoundedReadFromUnboundedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandler.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/dataflow/DataflowUnboundedReadFromBoundedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/Combine.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/ReadTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandlerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/dataflow/DataflowUnboundedReadFromBoundedSourceTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataEvaluator.java
Backport display data changes from:
- [#607 Mark primitive display data tests RunnableOnService](https://github.com/apache/incubator-beam/pull/607)
- [#1029 Correctly implement display data for DataflowRunner Read transforms](https://github.com/apache/incubator-beam/pull/1029)
- [#1034 PipelineOptions display data needs to handle array types](https://github.com/apache/incubator-beam/pull/1034)
=> Backport display data fixes

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/AvroSource.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroSourceTest.java
https://github.com/apache/incubator-beam/pull/1109
Diff (Apache Beam on left, Dataflow on right):
AvroSource.java:
```
2,8c2
<  * Licensed to the Apache Software Foundation (ASF) under one
<  * or more contributor license agreements.  See the NOTICE file
<  * distributed with this work for additional information
<  * regarding copyright ownership.  The ASF licenses this file
<  * to you under the Apache License, Version 2.0 (the
<  * "License"); you may not use this file except in compliance
<  * with the License.  You may obtain a copy of the License at
---
>  * Copyright (C) 2015 Google Inc.
10c4,8
<  *     http://www.apache.org/licenses/LICENSE-2.0
---
>  * Licensed under the Apache License, Version 2.0 (the "License"); you may not
>  * use this file except in compliance with the …
```
=> Backport Apache Beam PR #1109

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/join/UnionCoder.java
This is useful because users may need to construct a CoGbkResultCoder, and to construct a CoGbkResult Coder you need to construct a UnionCoder. E.g. see http://stackoverflow.com/questions/40367387/how-do-i-setcoders-when-doing-an-end-to-end-test-when-my-coder-requires-a-kvcode
UnionCoder is already public in Apache Beam.
R: @lukecwik
=> Makes UnionCoder public

contrib/sorter/AUTHORS.md, contrib/sorter/README.md, contrib/sorter/pom.xml, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/BufferedExternalSorter.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/ExternalSorter.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/InMemorySorter.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/SortValues.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/Sorter.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/package-info.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/BufferedExternalSorterTest.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/ExternalSorterTest.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/InMemorySorterTest.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/SortValuesTest.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/SorterTestUtils.java
A contrib module that provides a PTransform which performs
local(non-distributed) sorting. It will sort in memory until the buffer
is full, then flush to disk and use external sorting.
Consumes a PCollection of KVs from primary key to iterable of secondary
key and value KVs and sorts the iterables. Would probably be called
after a GroupByKey. Uses coders to convert secondary keys and values
into byte arrays and does a lexicographical comparison on the secondary
keys.
Uses Hadoop as an external sorting library.
Backport of https://github.com/apache/incubator-beam/pull/1199
=> Add SortValues

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSink.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/FileBasedSinkTest.java
This is a weaker but backward-compatible version of #482.
R: @dhalperi @lukecwik
=> FileBasedSink removes temp files from successful bundles

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/Transport.java
Beam already does this; this will make DataflowPipelineJob.cancel() non-flaky.
=> Use a retrying Dataflow Client for DataflowPipelineJob

pom.xml
This is a backport of apache/incubator-beam#1205 and subsequent improvements. It also demonstrates that fiddling with `sdk.properties` does not affect rebuilds.
I have confirmed locally that builds are idempotent with both JDK8 and JDK7. Additional confirmation welcome.
R: @dhalperi
=> Suppress spurious rebuilds due to missing package-info.class

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BatchTimerInternals.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GroupAlsoByWindowViaWindowSetDoFn.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PaneInfoTracker.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnContextFactory.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/TriggerRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/WatermarkHold.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BatchTimerInternalsTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/ReduceFnTester.java
- add prefetch* methods for prefetching state matching existing methods
- prefetch triggers in processElements
- replace onTimer with batched onTimers method to allow prefetching across
timers
=> Improve ReduceFnRunner prefetching

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/LateDataDroppingDoFnRunner.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/LateDataDroppingDoFnRunnerTest.java
=> Increase counters in LateDroppingDoFnRunner once, even with many iterations

contrib/kafka/src/main/java/com/google/cloud/dataflow/contrib/kafka/KafkaIO.java, contrib/kafka/src/test/java/com/google/cloud/dataflow/contrib/kafka/KafkaIOTest.java
KafkaIO should return one split for each of partition.
This is the actual unit of parallelism for Kafka topic. desiredNumSplits that Dataflow passes to a custom source is very low when maxNumWorkers is set. It asks for
just one split for each of the workers. This limits use of CPU cores on the workers essentially making autoscaling use more resources without improving performance.
This includes a hack to force single split in many unit tests since DirectPipelineRunner and InProcessPipelineRunner don't seem to read from more than one split.
=> KafkaIO should return one split for each of partition.

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CompressedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSink.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/io/XmlSink.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/dataflow/ReadTranslator.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/XmlSinkTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunnerTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslatorTest.java
R: @dhalperi 
https://github.com/apache/incubator-beam/pull/1545
https://github.com/apache/incubator-beam/pull/1475
https://github.com/apache/incubator-beam/pull/1134
=> Backport TextIO ValueProvider changes [BEAM-551]

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/TemplatingDataflowPipelineRunner.java
R: @dhalperi 
Using custom IO for this anticipates working with Beam, and supports better iteration by not requiring service cooperation for template execution.  The data cleanup regressions are suboptimal, but acceptable.
=> Templated jobs should use custom IO for BigQuery

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSource.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/FileBasedSourceTest.java
Typically, input file patterns are validated during Pipeline
construction, but standard Read transforms include an option to disable
validation. This is generally useful but can lead to cases where a
Pipeline executes successfully with empty inputs.
This changes the behavior to fail execution on empty file-based inputs
even when validation is disabled.
=> Backport: [BEAM-1160] Fail to split in FileBasedSource if filePattern expands to empty

contrib/sorter/README.md, contrib/sorter/pom.xml, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/BufferedExternalSorter.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/ExternalSorter.java, contrib/sorter/src/main/java/com/google/cloud/dataflow/contrib/sorter/InMemorySorter.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/BufferedExternalSorterTest.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/ExternalSorterTest.java, contrib/sorter/src/test/java/com/google/cloud/dataflow/contrib/sorter/InMemorySorterTest.java
Includes:
* Limit max memory for ExternalSorter and BufferedExternalSorter to 2047 MB to prevent int overflow within Hadoop's sorting library
* Fix int overflow for large memory values in InMemorySorter
* Add note about estimated disk use to README.MD
* Fix to make Hadoop's sorting library put all temp files under the specified directory
* Have Hadoop clean up the temp directory on exit
* Stop shading hadoop dependencies. Some context:
** The existing shading is broken (modules that depend on this one cannot use it successfully).
** Hadoop's use of reflection in several instances makes shading the dependency "in a good way" nearly impossible. It requires a couple of rather brittle hacks, and, for clients that depend on certain conflicting versions of hadoop these hacks can mean it doesn't …
=> Backport apache/incubator-beam#1327

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/View.java
Backport of https://github.com/apache/incubator-beam/pull/1650
=> View: javadoc fixes to asMap

pom.xml
Confirmed manually:
```
➜  DataflowJavaSDK git:(java8-require) ✗ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Google Cloud Dataflow SDK for Java - Parent
[INFO] Google Cloud Dataflow SDK for Java - All
[INFO] Google Cloud Dataflow Java Examples - All
[INFO] Google Cloud Dataflow SDK for Java - Starter Archetype
[INFO] Google Cloud Dataflow SDK for Java - Examples Archetype
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Dataflow SDK for Java - Parent …
```
=> maven-enforcer: require Java 1.8.0 and above

contrib/kafka/README.md, contrib/kafka/pom.xml
Recent PR #491 changes how KafkaIO splits. This makes it incompatible
with Dataflow update across these two versions.
=> Increase KafkaIO version to 0.2.0

sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/AvroCoder.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/coders/AvroCoderTest.java
This is a back port of a BEAM-359. It allows to create a coder for generics in a case if the schema for the concrete type parameter is provided. The created coder will be treated as non-deterministic.
For more information look at: 
https://issues.apache.org/jira/browse/BEAM-359
https://github.com/apache/beam/commit/9c8dc4fe920618253b425f0d998f8d63552ec358
http://stackoverflow.com/questions/41381648/serializing-generic-class-with-provided-schema-using-avrocoder
=> [BEAM-359] Treat erased type variables as non-deterministic in AvroCoder

maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml, maven-archetypes/examples/src/main/resources/archetype-resources/src/main/java/DebuggingWordCount.java, maven-archetypes/examples/src/main/resources/archetype-resources/src/main/java/WordCount.java, maven-archetypes/examples/src/main/resources/archetype-resources/src/test/java/WordCountTest.java, maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml, maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml, pom.xml
This is based on the release candidate #2, currenly being considered as the release.
Lots of manual work, double-checking would be beneficial. This goes to `v2` branch, before an RC is cut. Some stuff comes later (archetype versioning, container image).
=> Upgrade to Apache Beam, version 0.5.0

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSource.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PubsubTestClient.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSourceTest.java
=> Fix InProcessPipelineRunner to handle a null subscription

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java, sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java
We created a helper in BigQueryIO to create a JobConfigurationQuery capturing all options, but we had not yet propagated this cleanup into the Services abstraction or helper classes.
Refactor BigQueryServices and BigQueryTableRowIterator to propagate the same configuration.
Adds a new deprecated constructor to BigQueryTableRowIterator for backwards-compatibility.
This fixes GoogleCloudPlatform/DataflowJavaSDK#539.
=> BigQuery: fix an issue with option propagation and refactor to future-proof

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java
2 line bugfix for the finalize() method
=> Small fix for BigtableIO's WriteOperation.finalize

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJob.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJobTest.java
This is a backport of BEAM-1880 https://github.com/apache/beam/pull/2428
=> DataflowPipelineJob: gracefully handle cancellation concurrent with termination

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
This is a backport of https://github.com/apache/beam/pull/2594
R: @dhalperi
=> Cache result of BigQuerySourceBase.split

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
Backport of https://github.com/apache/beam/pull/2635
=> Makes cachedSplitResult transient in BigQuerySourceBase

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CompressedSource.java, sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CompressedSourceTest.java
Configure BZIP2 to read all "streams"
Without this, CompressionMode.BZIP2 only supports "standard" bz2 files
containing a single stream. With this change, BZIP2 also supports bz2
files containing multiple streams, such as those produced by pbzip2.
=> Backport apache/beam #3669

maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml, maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml
=> Fix undefined property bug

sdk/pom.xml, sdk/src/main/java/com/google/cloud/dataflow/sdk/SdkDependencies.java
Also removing fail-on-warning for Dependency Plugin, as Kafka dependency is not used anywhere and this makes analyze-dependencies fail.
This is because Maven Dependency Pluging analyzes bytecode and if a dependency is not used but declared, generates a warning.
r: @lukecwik
=> Adding Kafka IO to Dataflow SDK dependencies
