GoogleCloudPlatform/DataflowJavaSDK

sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/Proto2Coder.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/coders/Proto2CoderTest.java

Introduces proto2 coder support for Cloud Dataflow.

Introduces Proto2Coder.

---

.gitignore

As talked about in https://github.com/GoogleCloudPlatform/DataflowJavaSDK/pull/10

Ignore files created by Intellij.

---

.gitignore

Ignored the following additional IntelliJ files:
* The *.ipr file stores settings related to a project in general, for example, paths to modules and module libraries, compiler and configurations, entry points, etc.
* The *.iws file contains workspace with your personal settings, for example, opened files, folding, preferences for VCS, Local History, Run/Debug configurations, etc.

Ignore additional IntelliJ files.

---

examples/README.md

Issue #45 Fix broken links

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java

Fixes https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/71.

Update BQ date range output docs.

---

.travis.yml

See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
"""
Jobs running on container-based infrastructure:
1. Start up faster
2. Allow the use of caches for public repositories
3. disallow the use of sudo, setuid, and setgid
"""

Enable Travis container-based infrastructure

---

contrib/join-library/README.md
contrib/join-library/pom.xml
contrib/join-library/src/main/java/com/google/cloud/dataflow/contrib/joinlibrary/Join.java
contrib/join-library/src/test/java/com/google/cloud/dataflow/contrib/joinlibrary/InnerJoinTest.java

As follow up to https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/97 this is an adaption of the join-library contrib module to be able to upload it to maven-central.

Adapt to be able to upload to maven-central

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java

Sources should start from the beginning of a pipeline.

Backport apache/incubator-beam#18

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/IntervalBoundedExponentialBackOff.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserterTest.java

backport of apache/incubator-beam#107

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/SourceTestUtils.java

backport apache/incubator-beam#144

[BEAM-182] Bound trials in assertSplitAtFraction

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/DataflowPipelineOptions.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/options/PipelineOptions.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunnerTest.java

It is back ported from:
https://github.com/apache/incubator-beam/pull/44

Move tempLocation to PipelineOptions.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityEnforcementFactory.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineOptions.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoInProcessEvaluator.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityEnforcementFactoryTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java

This backports [BEAM #129](https://github.com/apache/incubator-beam/pull/129)

Apply ModelEnforcement in the InProcessPipelineRunner

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java

This backports [Beam #143](https://github.com/apache/incubator-beam/pull/143)

Free references to empty TransformExecutorServices

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java

Use an AtomicReference to ensure the thread the Executor is being run on
will be visible to other threads.
Add a checkState to ensure that the executor will not run more than
once.
Stop setting the active thread to null, as the Transform Executor should
be discarded from any references and not hold the overall execution.
This backports [BEAM #161](https://github.com/apache/incubator-beam/pull/161)

Fix multithreaded visibility issue with TransformExecutor

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImplTest.java

This is back ported from:
https://github.com/apache/incubator-beam/pull/48

Implement BigQueryIO.Write as a sink

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoInProcessEvaluator.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoMultiEvaluatorFactory.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoSingleEvaluatorFactory.java

This Backports [BEAM #188](https://github.com/apache/incubator-beam/pull/188)

Improve ParDoEvaluator Factoring.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/UserCodeException.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/UserCodeExceptionTest.java

R: @davorbonaci 
Should consider for 1.5.2 if there is one.

[BEAM-204] Backport https://github.com/apache/incubator-beam/pull/221/files

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ParDoInProcessEvaluator.java

This backports [BEAM #227](https://github.com/apache/incubator-beam/pull/227#issuecomment-213129070)

Wrap Exceptions thrown in StartBundle in the InProcessPipelineRunner

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/AvroIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CountingInput.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CountingInputTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/PubsubIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIOTest.java

Register DisplayData from composite IO transforms
(cherry picked from commit 15b11edef1e24fbffaa37b57494746d53522e04e)

Backport changes for DisplayData composite IO

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/Counter.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/common/CounterTest.java

Backport Beam: https://github.com/apache/incubator-beam/pull/219

Add DirtyBit to represent whether Counters have been committed.

---

checkstyle.xml
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ImmutabilityCheckingBundleFactory.java

This is a partial backport of https://github.com/apache/incubator-beam/pull/270

DataflowJavaSDK: blacklist Throwables.propagate

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSink.java

Backport of apache/incubator-beam#306

FileBasedSink: fix a format string bug

---

maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
pom.xml
sdk/pom.xml

Backport of apache/incubator-beam#303
I have not inspected the backport auto-merge closely but I will.
R: @lukecwik

pom.xml: upgrade to version 1.22.0 of the Google API client libs

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadEvaluatorFactory.java

Backports [Beam #289](https://github.com/apache/incubator-beam/pull/289)

Explicitly use a ConcurrentLinkedQueue in UnboundedReadEvaluatorFactory

---

examples/src/main/java/com/google/cloud/dataflow/examples/common/DataflowExampleUtils.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BoundedReadFromUnboundedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/BlockingDataflowPipelineRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineJob.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/IntraBundleParallelization.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GcsUtil.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/IntraBundleParallelizationTest.java

Backport: https://github.com/apache/incubator-beam/pull/45

Backport PR from Beam: "Re-interrupt current thread when ignoring InterruptedException"

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImplTest.java

Backport: https://github.com/apache/incubator-beam/pull/285

Backport PR from Beam: "Refactor BigQueryServices to support extract and query jobs"

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/WatermarkCallbackExecutor.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManagerTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContextTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/WatermarkCallbackExecutorTest.java

Backports [Beam #312](https://github.com/apache/incubator-beam/pull/312)

Update Watermarks outside of WatermarkManager#handleResult

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSink.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GcsUtil.java

Backport: https://github.com/apache/incubator-beam/pull/295

Backport PR from Beam: Move copy and remove from FileBasedSink to GcsUtil.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImplTest.java

backport apache/incubator-beam#190

Implement BigQueryIO.Read as BoundedSource

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java

Also, inline the constant and deprecate the one in BigQueryIO.java

BatchBigQueryIONativeReadTranslator: fixup format string

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/worker/IsmFormat.java

This reverts parts of commit c18c58f0722d2a6d97c4a8cfb62a7fb858d01bf5
to move IsmFormat.java to AutoValue. It keeps AutoValue integration
which other classes depend on.

Revert IsmFormat AutoValue conversion

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/DataflowPipelineDebugOptions.java

Backport windmill service endpoint option to Dataflow
r=@kennknowles

[BEAM-271] Option to configure remote Dataflow windmill service endpoint

---

checkstyle.xml
examples/src/main/java8/com/google/cloud/dataflow/examples/complete/game/injector/Injector.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/CoderFactories.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DirectPipelineRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/GroupByKey.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/Partition.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/join/CoGbkResult.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/join/UnionCoder.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableInserter.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/InstanceBuilder.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/StringUtils.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/Transport.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/values/PCollectionList.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutorTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataMatchers.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/values/PCollectionListTest.java

We should do it consistently throughout the SDK. Only a few
fixups.
Ported from: https://github.com/checkstyle/checkstyle/blob/ccdc3c09c500ccd31d56e4d6ed9c2d86edf2e9f1/src/main/resources/google_checks.xml#L167
This is a backport of https://github.com/apache/incubator-beam/pull/341

checkstyle: enforce where line breaks happen

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/Combine.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataEvaluatorTest.java

Backport of apache/incubator-beam#360

DisplayData: a few build fixups

---

contrib/hadoop/src/main/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/AvroSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BlockBasedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BoundedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CompressedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CountingSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/DatastoreIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/OffsetBasedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/range/OffsetRangeTracker.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CompressedSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CountingSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/FileBasedSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/OffsetBasedSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/range/OffsetRangeTrackerTest.java

And implement it for common sources

BoundedReader: add getSplitPoints{Consumed,Remaining}

---

sdk/pom.xml
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSink.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/MovingFunction.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PubsubClient.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/PubsubJsonClient.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BucketingFunctionTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/MovingFunctionTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/PubsubClientTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/PubsubGrpcClientTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/PubsubJsonClientTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/PubsubTestClientTest.java

R: @dhalperi 
Something like this we think.
Will test later today.
Any tips for running tap without hand patching?

Fiddle with rewrites so dataflow graph remains identical

---

contrib/hadoop/src/main/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/AvroSource.java

Two minor changes caught by internal builds

Limited parallelism fixup

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSource.java

Backport BEAM pull/388 for BEAM-306

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ActiveWindowSet.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/MergingActiveWindowSet.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/NonMergingActiveWindowSet.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunner.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/MergingActiveWindowSetTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/TriggerTester.java

Backport BEAM/pull/380 for BEAM-299

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/WatermarkHold.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/ReduceFnRunnerTest.java

Backport BEAM pull/391 for BEAM-122 and BEAM-311

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java

DataflowPipelineRunner: increment API version

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java

Ensure that the executor service is shutdown, and the monitor is not
rescheduled, after an exception is thrown.
Backports https://github.com/apache/incubator-beam/pull/435

Shutdown the InProcessPipelineRunner after Terminating Abnormally

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java

This ensures that a call to ExecutorService#awaitCompletion returns immediately
if there are no visible updates and the executor has completed. If the executor is
in this state, no additional visible updates will be published and the call will hang.
This sequence generally will not happen, as calls via InProcessPipelineResult
return if the state is already terminal, but this ensures that parallel calls to
awaitCompletion do not hang one calling thread.
Backports https://github.com/apache/incubator-beam/pull/399

Return from awaitCompletion if Already Done

---

examples/src/main/java/com/google/cloud/dataflow/examples/complete/AutoComplete.java

(cherry picked from commit e60e3e6de85a022d4669333c544b0b86145d0d55)

Fix AutoComplete example streaming configuration

---

.travis.yml
pom.xml

Spiritual backport of https://github.com/apache/incubator-beam/pull/551

Configure Surefire Argline in Travis

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/dataflow/DataflowUnboundedReadFromBoundedSource.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunnerTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/dataflow/DataflowUnboundedReadFromBoundedSourceTest.java

Backport Beam PR: https://github.com/apache/incubator-beam/pull/550/files

Backport from Beam: Use UnboundedReadFromBoundedSource in dataflow runner

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/worker/StateSampler.java

Encapsulate the logic to using SheduledExecutorService inside the
current default scheduler.

Refactor StateSampler with parameterized schedule

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/util/ApiSurfaceTest.java

Remove reference to non-existent class.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/DataflowReleaseInfo.java

Release Info: fix official name of SDK

---

sdk/pom.xml

Also part of Bigtable public API surface

sdk-all: do not repackage BulkOptions

---

.travis.yml
contrib/kafka/pom.xml
contrib/kafka/src/main/java/com/google/cloud/dataflow/contrib/kafka/KafkaCheckpointMark.java
contrib/kafka/src/main/java/com/google/cloud/dataflow/contrib/kafka/KafkaIO.java
contrib/kafka/src/main/java/com/google/cloud/dataflow/contrib/kafka/KafkaRecord.java
contrib/kafka/src/main/java/com/google/cloud/dataflow/contrib/kafka/KafkaRecordCoder.java
contrib/kafka/src/main/java/com/google/cloud/dataflow/contrib/kafka/package-info.java
contrib/kafka/src/test/java/com/google/cloud/dataflow/contrib/kafka/KafkaIOTest.java
pom.xml

KafkaIO is an Unbounded source for reading from Apache Kafka.
Backports KafkaIO from Apache Beam. See apache/incubator-beam
7b175dff8303b24cb92702db5b5a1a4691435bb1

Add KafkaIO to Contrib

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/DoFnTester.java

- Porting this from https://github.com/apache/incubator-beam/pull/697

Add option to disable cloning DoFn in DoFnTester

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CompressedSource.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CompressedSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java

This is a backport of
https://github.com/apache/incubator-beam/pull/794
and
https://github.com/apache/incubator-beam/pull/504

Compressed source fixes and tests

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandlerTest.java

This tests the equality groups instead of manual assertions, including
same-reference equality.

Use EqualsTester in ProxyInvocationHandlerTest

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/V1Beta3.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/datastore/V1Beta3Test.java

- Porting this change from https://github.com/apache/incubator-beam/pull/739

Datastore Read as a composite PTransform

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/ExecutorServiceParallelExecutor.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessEvaluationContext.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/TransformExecutor.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/InProcessPipelineRunnerTest.java

backports https://github.com/apache/incubator-beam/pull/795
backports https://github.com/apache/incubator-beam/pull/811

Minor Cleanups in the Direct Runner

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslator.java

This is a backpot of BEAM-804.

Do not add DataDisks to windmill service jobs.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java

Backports apache/incubator-beam#832

Corrected BigQueryIO javadoc

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/StepTransformResult.java

backports https://github.com/apache/incubator-beam/pull/746

Use AutoValue for StepTransformResult

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/JAXBCoder.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/coders/JAXBCoderTest.java

JAXB Marshaller and Unmarshaller are not thread safe, but coders are
required to be.
Create context only once, and create Marshaller and Unmarshaller locally
on-demand.
backports https://github.com/apache/incubator-beam/pull/497

Make JAXBCoder Thread Safe

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java

R: @dhalperi 
CC: @peihe @lukecwik

Import Strings utilities from guava instead of google.api.client

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServices.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryServicesImpl.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java

BigQueryIO update sink to shard into multiple write jobs

---

examples/src/test/java/com/google/cloud/dataflow/examples/cookbook/TriggerExampleTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/XmlSourceTest.java

TriggerExampleTest uses an equality method that does not match the assumptions
made by the test for qualities that make rows equal.
Use an explicit coder in XMLSourceTest to avoid having to make a change
to the underlying behavior of JAXBCoder that may be backwards incompatible
in some cases.

Backport TriggerExampleTest fixes, Fix XMLSourceTest

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/V1Beta3.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/datastore/V1Beta3Test.java

- Backport from https://github.com/apache/incubator-beam/pull/845
- SimpleFunction in DF SDK doesn't extend 'HasDisplayData', hence moving that to the PTransform. This is the only difference.

Datastore Sink support for writing Mutations.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GcsUtil.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/GcsUtilTest.java

This is a backport of apache/incubator-beam#826

FileBasedSink: improve parallelism in GCS copy/remove

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/testing/WindowSupplierTest.java

backport of apache/incubator-beam#873

WindowSupplierTest: add missing @RunWith

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/Write.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunnerTest.java

This also back ports https://github.com/apache/incubator-beam/pull/802

Enable TextIO.Write in DataflowPipelineRunner for streaming

---

examples/pom.xml
examples/src/main/java/com/google/cloud/dataflow/examples/complete/AutoComplete.java
examples/src/main/java/com/google/cloud/dataflow/examples/cookbook/DatastoreWordCount.java
pom.xml
sdk/pom.xml
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1Test.java

- Backport from https://github.com/apache/incubator-beam/pull/858

DatastoreIO v1beta3 to v1 version

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/TestPipeline.java

Fix TestPipeline javadoc to correspond with current implementation.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/Counter.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/CounterSet.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/common/NameContext.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/common/CounterSetTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/common/CounterTest.java

This CL adds support for structured names and tests in the batch dataflow worker

Add structured name support to dataflow batch worker

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1Test.java

- Back port from https://github.com/apache/incubator-beam/pull/868

DatastoreIO statistics query fixes

---

examples/src/main/java/com/google/cloud/dataflow/examples/complete/AutoComplete.java
examples/src/main/java/com/google/cloud/dataflow/examples/cookbook/DatastoreWordCount.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/package-info.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreV1Test.java

- Backport of https://github.com/apache/incubator-beam/pull/911

Cloud Datastore naming clean-up

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java

Backport https://github.com/apache/incubator-beam/pull/918

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java

Upgrade the worker container version

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRunner.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/coders/EntityCoderTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/AvroSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/CountingSourceTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/DatastoreIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/DirectPipelineRunnerTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/IntervalBoundedExponentialBackOffTest.java

SDK: suppress expected deprecation warnings

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/FlattenTest.java

This test demonstrates that if a Flatten.PCollections transform has the
same PCollectionList in its input multiple times, it will duplicate the
input PCollection for each time it occurs within the list.
Backports https://github.com/apache/incubator-beam/pull/960

Add Flatten with Duplicate Inputs Test

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/AvroUtils.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/AvroUtilsTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java

Backport: https://github.com/apache/incubator-beam/pull/977
R: @lukecwik

Backport Beam-977: Support BigQuery BYTES type

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/PipelineTest.java

https://github.com/apache/incubator-beam/pull/993
R: @swegner

Backport Apache Beam 993 

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java

Add the removed public API back for backward compatibility.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/AvroUtils.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/AvroUtilsTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java

Backport:
https://github.com/apache/incubator-beam/pull/997
https://github.com/apache/incubator-beam/pull/985

Backport BEAM-985 and BEAM-997: Support BigQuery DATE, DATETIME and TIME types

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CompressedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/TextIOTest.java

This is a backport of apache/incubator-beam#980
R: @jkff please review for backporting errors

TextIO/CompressedSource: support splitting AUTO mode files into bundles

---

checkstyle.xml
contrib/firebaseio/src/main/java/com/google/cloud/dataflow/contrib/firebase/io/FirebaseSource.java
contrib/hadoop/src/main/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSource.java
contrib/join-library/src/main/java/com/google/cloud/dataflow/contrib/joinlibrary/Join.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/CompressedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/FileBasedSource.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/TextIO.java

A spiritual backport of apache/incubator-beam#1030

checkstyle: enforce static import from Preconditions

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIterator.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/util/BigQueryTableRowIteratorTest.java

Forward port fixups in
https://github.com/apache/incubator-beam/pull/1032

Forward port fixups in Beam PR-1032

---

examples/pom.xml
maven-archetypes/examples/pom.xml
maven-archetypes/starter/pom.xml
pom.xml
sdk/pom.xml

Begin version 1.9.0 of the Dataflow SDK for Java

Version management

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DirectPipelineRunner.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BoundedReadFromUnboundedSourceTest.java

Use encoded Elements in the DirectPipelineRunner

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/DataflowPipelineOptions.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineTranslator.java

Add serviceAccount option to Dataflow

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/inprocess/InMemoryWatermarkManager.java

This removes an O(n) call to remove, replacing it with an O(log(n))
call. This significantly improves scaling behavior of the DirectRunner
Backports https://github.com/apache/incubator-beam/pull/1202

Use a NavigableSet Instead of a PriorityQueue in WatermarkManager

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/coders/AvroCoder.java

https://github.com/apache/incubator-beam/commit/752a8da377d8bb17a61826bd7e00bd3798c23881
R: @tgroh

Backport Apache Beam PR #1322

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/PipelineOptions.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/options/PipelineOptionsFactory.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandler.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/options/ValueProvider.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/options/ValueProviderUtils.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayData.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/util/ApiSurface.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/options/PipelineOptionsFactoryTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/options/PipelineOptionsTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/options/ProxyInvocationHandlerTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/options/ValueProviderTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/options/ValueProviderUtilsTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/transforms/display/DisplayDataTest.java

Backport ValueProvider from [BEAM-551]

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java

Backport apache/incubator-beam#1238

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubIO.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSink.java
sdk/src/main/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSource.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/PubsubIOTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSinkTest.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/PubsubUnboundedSourceTest.java

R: @dhalperi 
Pulled in changes for PubsubUnbounded*.java from https://github.com/apache/incubator-beam/pull/1504

Backport https://github.com/apache/incubator-beam/pull/1230

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/options/PipelineOptionsFactory.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/options/PipelineOptionsFactoryTest.java

Backport of https://github.com/apache/incubator-beam/pull/1580

Allow empty string value for ValueProvider types.

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java

Fix handling of streaming BQ table

---

sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java
sdk/src/test/java/com/google/cloud/dataflow/sdk/io/BigQueryIOTest.java

Fix null project error

---

contrib/firebaseio/pom.xml
contrib/hadoop/pom.xml
contrib/join-library/pom.xml
contrib/kafka/pom.xml
contrib/sorter/pom.xml
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml

Cherry-pick into 1.9 hotfix branch.

Update version range dependency to exclude 2.0.0-betaX versions (#528)

---

maven-archetypes/examples-java8/src/main/resources/archetype-resources/pom.xml
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml
pom.xml

Versioning in the release branch for 2.0.0-beta3

---

maven-archetypes/examples-java8/src/main/resources/archetype-resources/pom.xml
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml
pom.xml

Update versioning after cutting 2.0.0-beta3 release branch

---

maven-archetypes/examples-java8/src/main/resources/archetype-resources/pom.xml
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
pom.xml

`Starter` reference intentionally not touched. Opinions on this?

Archetypes: version management at the top-level outside archetype source code

---

maven-archetypes/examples-java8/src/main/resources/archetype-resources/pom.xml
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
pom.xml

Signed-off-by: Jason Kuster <jasonkuster@google.com>

Versioning in the release branch for 2.0.0

---

pom.xml
sdk/src/main/resources/org/apache/beam/runners/dataflow/dataflow.properties

dataflow.properties: update for new configuration in Apache Beam 2.0.0
See https://github.com/apache/beam/commit/b6508977e56e18903f2224e3a2a4ad9816ea1c89\#diff-2dcc904003e8cbcbf02e330b8be4c7db

Cherry-pick #575 into release-2.0.0 branch

---

pom.xml
sdk/src/main/resources/org/apache/beam/runners/dataflow/dataflow.properties

See https://github.com/apache/beam/commit/b6508977e56e18903f2224e3a2a4ad9816ea1c89\#diff-2dcc904003e8cbcbf02e330b8be4c7db

dataflow.properties: update for new configuration in Apache Beam 2.0.0

---

examples/pom.xml
maven-archetypes/examples/pom.xml
maven-archetypes/starter/pom.xml
pom.xml
sdk/pom.xml

Update maven versions to 1.9.1 in hotfix branch

Update maven versions to 1.9.1 in hotfix branch

---

maven-archetypes/examples-java8/src/main/resources/archetype-resources/pom.xml
maven-archetypes/examples-java8/src/main/resources/archetype-resources/src/test/java/complete/game/LeaderBoardTest.java
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml
pom.xml

Updated the compiler plugin version, and added explicit versioning for the JAR plugin.

Update to Apache Beam, v2.1.0.

---

maven-archetypes/examples-java8/src/main/resources/archetype-resources/pom.xml
maven-archetypes/examples/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/main/resources/archetype-resources/pom.xml
maven-archetypes/starter/src/test/resources/projects/basic/reference/pom.xml
pom.xml

This makes versioning consistent with the Beam POMs. The top-level POM
contains the version numbers, and versions are plumbed into the
archetypes via properties.

Refactor versioning information for archetypes.

---

sdk/src/test/java/com/google/cloud/dataflow/sdk/runners/inprocess/UnboundedReadDeduplicatorTest.java

Fixes slowdowns causing timeouts in certain environments.

Reduce Size of UnboundedReadDeduplicatorTest

---

examples/pom.xml
maven-archetypes/examples/pom.xml
maven-archetypes/pom.xml
maven-archetypes/starter/pom.xml
pom.xml
sdk/pom.xml

* Upgraded future the version number from 2.2.0 to 2.3.0, which should have had done when releasing 2.2.0
* released the launch from 2.3.0.
* Prepared for next release of 2.4.0.

Prepare for next development iteration

---

examples/pom.xml
maven-archetypes/examples/pom.xml
maven-archetypes/pom.xml
maven-archetypes/starter/pom.xml
pom.xml
sdk/pom.xml

This is to revert some of the changes made for 2.5.0 release (as it needs to be run again). this PR preserves history.
r: @lukecwik

Revert 2.5.0 release changes

---

examples/pom.xml
maven-archetypes/examples/pom.xml
maven-archetypes/pom.xml
maven-archetypes/starter/pom.xml
pom.xml
sdk/pom.xml

Prepare 2.5.0 release once more
